/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { NCPStakingGateway } from "./NCPStakingGateway";
export * as factories from "./factories";
export { NCPStakingGateway__factory } from "./factories/NCPStakingGateway__factory";
